### ISSUE TITLE
The plug-in didn't work for me in VitePress site

### ISSUE THREAD

**Issue by vedxp** [luckrya/markdown-it-link-to-card#1]
Here's the pr adding the plugin: [Visit](https://github.com/VedxP/reesors/pull/29)

**Comment by cllemon** [comment]
@VedxP Hi, thanks for your feedback, this is a bug, it has been fixed in `v0.3.2` !

**Comment by vedxp** [comment]
> @VedxP Hi, thanks for your feedback, this is a bug, it has been fixed in `v0.3.2` !

Sounds great, thanks for fixing :)

But, I even after updating to `0.3.2`, it's still the same :(

#### Here's the PR: [Visit](https://github.com/VedxP/reesors/pull/34)

#### I've changed urls of [this page](https://reesors-git-vedxp-patch-2-vedxp.vercel.app/sections/app),
from this:
```
[Link Title](https://test.com)
```
to this:
```
[Link Title](@:https://test.com)
```

**Comment by cllemon** [comment]
> > @vedxp Hi, thanks for your feedback, this is a bug, it has been fixed in `v0.3.2` !
> 
> Sounds great, thanks for fixing :)
> 
> But, I even after updating to `0.3.2`, it's still the same :(
> 
> #### Here's the PR: [Visit](https://github.com/VedxP/reesors/pull/34)
> #### I've changed urls of [this page](https://reesors-git-vedxp-patch-2-vedxp.vercel.app/sections/app),
> from this:
> 
> ```
> [Link Title](https://test.com)
> ```
> 
> to this:
> 
> ```
> [Link Title](@:https://test.com)
> ```

the incoming config does not correspond to the usage, you can:
remove `tag: '\\$'` and use the default tag value of '@' or change your URL to `[title]($:https://...)`

**Comment by cllemon** [comment]
@vedxp  Hi! It is recommended to use the latest version (`v0.3.3`), adding some character escapes to prevent compilation exceptions.

**Comment by cllemon** [comment]
@vedxp  Hi! It is recommended to use the latest version (`v0.3.3`), which adds some character escapes to prevent compilation exceptions. This upgrade needs to delete the local cache file (`.linkcardrc`) because it caches unescaped content

**Comment by vedxp** [comment]
> @vedxp Hi! It is recommended to use the latest version (`v0.3.3`), which adds some character escapes to prevent compilation exceptions. This upgrade needs to delete the local cache file (`.linkcardrc`) because it caches unescaped content

Great, thank you so much :)

**Comment by vedxp** [comment]
@cllemon that means I can write links like this:

```
- [github](@:https://github.com)
```
without any extra config?

**Comment by cllemon** [comment]
@vedxp If your configuration does not specify 'tag', then the plugin will use the default tag value `@`, ie `[link title](@:https://xxx)` for details, see https://github.com/luckrya/markdown-it-link-to-card#tag

**Comment by vedxp** [comment]
> @vedxp If your configuration does not specify 'tag', then the plugin will use the default tag value `@`, ie `[link title](@:https://xxx)` for details, see https://github.com/luckrya/markdown-it-link-to-card#tag

I haven't specified `tag` in config and changed a page's link like this: `[title](@:https://url)`

But still, preview card is not working.

[Visit the related PR](https://github.com/vedxp/reesors/pull/36)

I'm not sure what I'm doing wrong, help much appreciated :)

**Comment by vedxp** [comment]
> @vedxp If your configuration does not specify 'tag', then the plugin will use the default tag value `@`, ie `[link title](@:https://xxx)` for details, see https://github.com/luckrya/markdown-it-link-to-card#tag

Thank you for your help.

Can you please have a look why the preview card is breaking the layout?

[Here's the page link](https://reesors-izj85z16a-vedxp.vercel.app/sections/)

And even, some links don't render as card at all.

**Comment by cllemon** [comment]
@vedxp  ok, i'll take a look later
